// Generates src/environments/environment.prod.ts from env vars at build time.
// Run automatically via the "build" script in package.json before ng build.
const { writeFileSync } = require('fs');
const { resolve } = require('path');

const apiBaseUrl = process.env['API_BASE_URL'] ?? '';

const content = `// Auto-generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiBaseUrl: '${apiBaseUrl}',
};
`;

const outPath = resolve(__dirname, '../src/environments/environment.prod.ts');
writeFileSync(outPath, content, 'utf8');
console.log(`set-env: apiBaseUrl = "${apiBaseUrl}"`);
