// Generates src/environments/environment.prod.ts from env vars at build time.
// Run automatically via the "build" script in package.json before ng build.
// In production, apiBaseUrl is always '' — Angular uses relative /api/* paths
// which Vercel proxies to the Render backend via the API_BASE_URL rewrite rule.
const { writeFileSync } = require('fs');
const { resolve } = require('path');

const content = `// Auto-generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiBaseUrl: '',
};
`;

const outPath = resolve(__dirname, '../src/environments/environment.prod.ts');
writeFileSync(outPath, content, 'utf8');
console.log('set-env: apiBaseUrl set to "" (requests proxied via Vercel)');
